version: "3.9"

services:
  qwen-vl-chat:
    build:
        context: .
        dockerfile: Dockerfile.qwenopenai
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]